"""Output helpers for serialising relay lists."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable, Sequence

from .errors import RelayBuildError
from .transform import Relay

PAC_TEMPLATE = """// Generated by Mullvad Relay List Builder\nfunction FindProxyForURL(url, host) {{\n    var proxies = [\n{proxies}    ];\n\n    if (proxies.length === 0) {{\n        return \"DIRECT\";\n    }}\n\n    var index = Math.floor(Math.random() * proxies.length);\n    return proxies[index];\n}}\n"""


def _ensure_sequence(relays: Iterable[Relay]) -> Sequence[Relay]:
    return relays if isinstance(relays, Sequence) else list(relays)


def write_json(relays: Iterable[Relay], destination: Path) -> None:
    """Write relays to a JSON file."""
    items = _ensure_sequence(relays)
    try:
        data = [relay.to_dict() for relay in items]
        destination.write_text(json.dumps(data, indent=2) + "\n")
    except OSError as exc:  # pragma: no cover - disk error safeguard
        raise RelayBuildError(f"Failed to write JSON to {destination}: {exc}") from exc


def write_text(relays: Iterable[Relay], destination: Path) -> None:
    """Write relays in a pipe-delimited text format."""
    items = _ensure_sequence(relays)
    try:
        lines = [
            "|".join(
                [
                    relay.socks5_endpoint,
                    relay.city,
                    relay.country,
                    relay.ipv4,
                ]
            )
            for relay in items
        ]
        destination.write_text("\n".join(lines) + ("\n" if lines else ""))
    except OSError as exc:  # pragma: no cover - disk error safeguard
        raise RelayBuildError(f"Failed to write text to {destination}: {exc}") from exc


def write_pac(relays: Iterable[Relay], destination: Path) -> None:
    """Write relays to a PAC (Proxy Auto-Config) script."""
    items = _ensure_sequence(relays)
    try:
        proxy_lines = [
            f'        "SOCKS5 {relay.socks5_endpoint}"'
            for relay in items
        ]
        proxies_section = ",\n".join(proxy_lines)
        if proxies_section:
            proxies_section += "\n"
        content = PAC_TEMPLATE.format(proxies=proxies_section)
        destination.write_text(content)
    except OSError as exc:  # pragma: no cover - disk error safeguard
        raise RelayBuildError(f"Failed to write PAC to {destination}: {exc}") from exc


__all__ = ["write_json", "write_text", "write_pac"]
