"""Output helpers for serialising relay lists."""

from __future__ import annotations

import csv
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping, MutableMapping, Sequence

from .errors import RelayBuildError
from .transform import Relay
from .enrich import EnrichedRelay

PAC_TEMPLATE = """// Generated by Mullvad Relay List Builder\nfunction FindProxyForURL(url, host) {{\n    var proxies = [\n{proxies}    ];\n\n    if (proxies.length === 0) {{\n        return \"DIRECT\";\n    }}\n\n    var index = Math.floor(Math.random() * proxies.length);\n    return proxies[index];\n}}\n"""

CSV_COLUMNS = (
    "hostname",
    "socks5_hostname",
    "socks5_endpoint",
    "city",
    "country",
    "provider",
    "ipv4",
    "ipv6",
)


def _ensure_sequence(
    relays: Iterable[Relay | EnrichedRelay | Mapping[str, object]]
) -> Sequence[Relay | EnrichedRelay | Mapping[str, object]]:
    return relays if isinstance(relays, Sequence) else list(relays)


def write_json(
    relays: Iterable[Relay | EnrichedRelay | Mapping[str, object]],
    destination: Path,
) -> None:
    """Write relays to a JSON file."""
    items = _ensure_sequence(relays)
    try:
        data = []
        for relay in items:
            if hasattr(relay, "to_dict"):
                data.append(relay.to_dict())
            elif isinstance(relay, Relay):
                data.append(relay.to_dict())
            else:
                data.append(relay)
        destination.write_text(json.dumps(data, indent=2) + "\n")
    except OSError as exc:  # pragma: no cover - disk error safeguard
        raise RelayBuildError(f"Failed to write JSON to {destination}: {exc}") from exc


def write_text(
    relays: Iterable[Relay | EnrichedRelay | Mapping[str, object]],
    destination: Path,
) -> None:
    """Write relays as SOCKS5 URLs suitable for Mubeng and similar tools."""

    items = _ensure_sequence(relays)
    try:
        lines = []
        for relay in items:
            data = _coerce_relay(relay)
            endpoint = str(data.get("socks5_endpoint", ""))
            lines.append(f"socks5://{endpoint}")
        destination.write_text("\n".join(lines) + ("\n" if lines else ""))
    except OSError as exc:  # pragma: no cover - disk error safeguard
        raise RelayBuildError(f"Failed to write text to {destination}: {exc}") from exc


def write_pac(
    relays: Iterable[Relay | EnrichedRelay | Mapping[str, object]],
    destination: Path,
) -> None:
    """Write relays to a PAC (Proxy Auto-Config) script."""
    items = _ensure_sequence(relays)
    try:
        proxy_lines = []
        for relay in items:
            data = _coerce_relay(relay)
            endpoint = str(data.get("socks5_endpoint", ""))
            proxy_lines.append(f'        "SOCKS5 {endpoint}"')
        proxies_section = ",\n".join(proxy_lines)
        if proxies_section:
            proxies_section += "\n"
        content = PAC_TEMPLATE.format(proxies=proxies_section)
        destination.write_text(content)
    except OSError as exc:  # pragma: no cover - disk error safeguard
        raise RelayBuildError(f"Failed to write PAC to {destination}: {exc}") from exc

def _coerce_relay(
    relay: Relay | EnrichedRelay | Mapping[str, object]
) -> Mapping[str, object]:
    if isinstance(relay, EnrichedRelay):
        return relay.relay.to_dict()
    if isinstance(relay, Relay):
        return relay.to_dict()
    return relay


def _stringify(value: object) -> str:
    return "" if value is None else str(value)


def write_csv(
    relays: Iterable[Relay | EnrichedRelay | Mapping[str, object]],
    destination: Path,
) -> None:
    """Write relays to a CSV file with deterministic columns."""

    items = _ensure_sequence(relays)
    try:
        with destination.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(CSV_COLUMNS)
            for item in items:
                data = _coerce_relay(item)
                row = [
                    _stringify(data.get("hostname")),
                    _stringify(data.get("socks5_hostname")),
                    _stringify(data.get("socks5_endpoint")),
                    _stringify(data.get("city")),
                    _stringify(data.get("country")),
                    _stringify(data.get("provider")),
                    _stringify(data.get("ipv4")),
                    _stringify(data.get("ipv6")),
                ]
                writer.writerow(row)
    except OSError as exc:  # pragma: no cover - disk error safeguard
        raise RelayBuildError(f"Failed to write CSV to {destination}: {exc}") from exc


def _hash_file(path: Path) -> str | None:
    if not path.exists():
        return None
    digest = hashlib.sha256()
    try:
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(8192), b""):
                if not chunk:
                    break
                digest.update(chunk)
    except OSError as exc:  # pragma: no cover - filesystem guard
        raise RelayBuildError(f"Failed to hash artifact {path}: {exc}") from exc
    return digest.hexdigest()


def _normalise_artifacts(
    artifacts: Mapping[str, str | Path] | None
) -> MutableMapping[str, dict[str, Any]]:
    normalised: dict[str, dict[str, Any]] = {}
    if not artifacts:
        return normalised
    for name, location in artifacts.items():
        path = Path(location)
        normalised[name] = {
            "path": str(path),
            "sha256": _hash_file(path),
            "size_bytes": path.stat().st_size if path.exists() else None,
        }
    return normalised


def write_manifest(
    relays: Iterable[Relay | EnrichedRelay | Mapping[str, object]],
    destination: Path,
    *,
    filters: Mapping[str, Any] | None = None,
    verification: Mapping[str, Any] | None = None,
    artifacts: Mapping[str, str | Path] | None = None,
    metadata: Mapping[str, Any] | None = None,
) -> None:
    """Write a manifest describing the relay build run."""

    items = _ensure_sequence(relays)
    payload: dict[str, Any] = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "relay_count": len(items),
        "filters": dict(filters or {}),
        "verification": dict(verification or {}),
        "artifacts": _normalise_artifacts(artifacts),
        "metadata": dict(metadata or {}),
    }

    try:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    except OSError as exc:  # pragma: no cover - disk error safeguard
        raise RelayBuildError(f"Failed to write manifest to {destination}: {exc}") from exc


__all__ = ["write_json", "write_text", "write_pac", "write_csv", "write_manifest"]
